"""Meeting note creation from calendar events.

For each timed event on a given date, generates a meeting note in the configured
meetings folder using the meeting template. The note filename follows the pattern:

    YYYY-MM-DD-shortened-title[-organizer-lastname].md

The 'context' YAML field is generated by calling the Anthropic API (claude-haiku)
with the event metadata. Requires ANTHROPIC_API_KEY in the environment.
in config.
"""
from __future__ import annotations

import logging
import os
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

# Common words to strip when building a slug from an event title
_STOP_WORDS = frozenset({
    "a", "an", "the", "and", "or", "of", "in", "on", "at", "to", "for",
    "with", "about", "meeting", "call", "sync", "discussion", "chat",
    "check-in", "checkin", "standup", "stand-up", "catch-up", "catchup",
    "debrief", "session", "1on1", "1:1",
})


def _slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", " ", text)
    text = re.sub(r"[\s_]+", " ", text).strip()
    return re.sub(r"\s+", "-", text)


def _meaningful_words(title: str, max_words: int = 4) -> list[str]:
    words = _slugify(title).split("-")
    kept = [w for w in words if w and w not in _STOP_WORDS]
    return kept[:max_words]


def meeting_note_slug(event_date: date, title: str, organizer: dict | None) -> str:
    """Build the note filename stem (no .md extension)."""
    date_str = event_date.strftime("%Y-%m-%d")
    words = _meaningful_words(title)
    title_part = "-".join(words) if words else _slugify(title)[:30]

    organizer_part = ""
    if organizer and not organizer.get("is_me"):
        name = organizer.get("name", "")
        if name:
            last = name.strip().split()[-1]
            organizer_part = "-" + _slugify(last)

    return f"{date_str}-{title_part}{organizer_part}"


def _generate_context(event: dict[str, Any]) -> str:
    """Call claude-haiku to generate a 2-3 sentence context summary for the meeting note."""
    try:
        import anthropic
    except ImportError:
        log.warning("anthropic package not installed; skipping context generation")
        return ""

    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        log.warning("No ANTHROPIC_API_KEY; skipping context generation")
        return ""

    # Build a compact description of the event for the prompt
    parts = [f"Title: {event['title']}"]
    if event.get("start"):
        parts.append(f"Time: {event['start'].strftime('%Y-%m-%d %H:%M')}")
    if event.get("calendar_name"):
        parts.append(f"Calendar: {event['calendar_name']}")
    if event.get("location"):
        parts.append(f"Location: {event['location']}")
    if event.get("organizer") and not event["organizer"].get("is_me"):
        parts.append(f"Organizer: {event['organizer']['name']}")
    attendees = [a["name"] for a in event.get("attendees", []) if a["name"] and not a.get("is_me")]
    if attendees:
        parts.append(f"Attendees: {', '.join(attendees[:8])}")
    if event.get("notes"):
        # Trim long descriptions
        desc = event["notes"][:600]
        parts.append(f"Description: {desc}")

    event_summary = "\n".join(parts)

    prompt = (
        "You are helping populate a meeting note in an Obsidian knowledge vault. "
        "Given the calendar event details below, write 2-3 concise sentences for a "
        "'context' field. Cover: what this meeting is likely about, who the key people "
        "are and their likely role, and any relevant background. Be informative but brief.\n\n"
        f"{event_summary}"
    )

    try:
        client = anthropic.Anthropic(api_key=key)
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        text = message.content[0].text.strip()
        # Strip any markdown headers Claude may prepend, then collapse to one line
        text = re.sub(r"^#+\s+\S[^\n]*\n+", "", text).strip()
        text = re.sub(r"\s*\n\s*", " ", text)
        return text
    except Exception as exc:
        log.warning("Context generation failed: %s", exc)
        return ""


def create_meeting_note(
    event: dict[str, Any],
    event_date: date,
    vault_root: str,
    config,
) -> str | None:
    """Create a meeting note for the given event if one doesn't already exist.

    Returns the vault-relative path (without .md) for use as a wikilink, or None on failure.
    """
    cal_cfg = config.calendar
    slug = meeting_note_slug(event_date, event["title"], event.get("organizer"))
    meetings_path = Path(vault_root) / cal_cfg.meetings_folder
    note_path = meetings_path / f"{slug}.md"

    # Don't overwrite an existing note
    if note_path.exists():
        log.debug("Meeting note already exists: %s", note_path.name)
        return f"{cal_cfg.meetings_folder}/{slug}"

    # Load meeting template
    template_path = Path(vault_root) / cal_cfg.meeting_template
    if not template_path.exists():
        log.warning("Meeting template not found: %s", template_path)
        template_content = "---\ntime:\ntags:\n  - Meeting\nrelatedTo:\ncontext:\n---\n"
    else:
        template_content = template_path.read_text(encoding="utf-8")

    # Generate context via Claude
    context = _generate_context(event)

    # Build time string
    time_str = ""
    if event.get("start") and not event["is_all_day"]:
        time_str = event["start"].strftime("%Y-%m-%dT%H:%M:%S")

    organizer = event.get("organizer")
    organizer_name = ""
    if organizer and not organizer.get("is_me") and _is_human_organizer(organizer):
        organizer_name = organizer.get("name", "")

    # Substitute frontmatter fields and inject context into body
    content = _fill_frontmatter(template_content, time_str, organizer_name)
    content = _inject_context(content, context)

    # Append a logistics block with just the join link (if present)
    content = _append_logistics(content, event)

    meetings_path.mkdir(parents=True, exist_ok=True)
    note_path.write_text(content, encoding="utf-8")
    log.info("Created meeting note: %s", note_path.name)

    return f"{cal_cfg.meetings_folder}/{slug}"


def _fill_frontmatter(template: str, time_str: str, organizer_name: str) -> str:
    """Replace empty time: and organizer: fields in the YAML frontmatter."""
    lines = template.splitlines(keepends=True)
    in_frontmatter = False
    fence_count = 0
    result = []
    for line in lines:
        stripped = line.rstrip("\n")
        if stripped == "---":
            fence_count += 1
            in_frontmatter = fence_count == 1
            result.append(line)
            continue
        if in_frontmatter:
            if stripped == "time:" and time_str:
                result.append(f"time: {time_str}\n")
                continue
            if stripped == "organizer:" and organizer_name:
                result.append(f"organizer: {organizer_name}\n")
                continue
        result.append(line)
    return "".join(result)


def _inject_context(content: str, context: str) -> str:
    """Replace the {Insert context here} placeholder in the callout body."""
    if not context:
        return content
    return content.replace("{Insert context here}", context)


_NON_HUMAN_DOMAINS = {"group.calendar.google.com", "resource.calendar.google.com"}


def _is_human_organizer(organizer: dict) -> bool:
    """Return False for calendar group/resource IDs masquerading as organizers."""
    email = organizer.get("email", "")
    domain = email.split("@")[-1] if "@" in email else ""
    return domain not in _NON_HUMAN_DOMAINS


def _append_logistics(content: str, event: dict) -> str:
    """Append a ## Logistics block. Currently only includes a join link if present."""
    lines = ["## Logistics"]

    if event.get("video_url"):
        lines.append(f"- [Join]({event['video_url']})")
    elif event.get("location"):
        lines.append(f"- Location: {event['location']}")

    if len(lines) == 1:
        return content  # nothing to add

    block = "\n".join(lines) + "\n"
    if not content.endswith("\n"):
        content += "\n"
    return content + "\n" + block
